# tap "earthly/earthly"
# tap "weaveworks/tap"
tap "cloudflare/cloudflare"
tap "fluxcd/tap"
tap "heroku/brew"
tap "homebrew/bundle"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "mongodb/brew"
tap "thoughtbot/formulae"
tap "vmware-tanzu/carvel"

# brew "calicoctl"
# brew "earthly/earthly/earthly"
# brew "graphviz"
# brew "hey"
# brew "hivemind"
# brew "jpegoptim"
# brew "librsvg"
# brew "libxslt"
# brew "optipng"
# brew "pinentry-mac"
# brew "telnet"
# brew "urlview"
# brew "weaveworks/tap/eksctl"
brew "argocd"
brew "autoconf"
brew "automake"
brew "awscli"
brew "caddy"
brew "cairo"
brew "cloudflare/cloudflare/cloudflared"
brew "cmake"
brew "confuse"
brew "coreutils"
brew "ctags"
brew "curl"
brew "fluxcd/tap/flux"
brew "fontconfig"
brew "freetype"
brew "gdbm"
brew "gettext"
brew "git"
brew "glib"
brew "gnupg"
brew "heroku/brew/heroku"
brew "htop"
brew "iftop"
brew "imagemagick"
brew "iperf3"
brew "jpeg"
brew "jq"
brew "k6"
brew "kind"
brew "kops"
brew "kubectx"
brew "kubeseal"
brew "kubie"
brew "kustomize"
brew "libevent"
brew "libffi"
brew "libpng"
brew "libtiff"
brew "libtool"
brew "libyaml"
brew "linkerd"
brew "mas"
brew "mkcert"
brew "mongodb/brew/mongodb-community-shell"
brew "nginx"
brew "node"
brew "nss"
brew "openconnect"
brew "openssl@1.1"
brew "overmind"
brew "pango"
brew "pcre"
brew "perl"
brew "pgcli"
brew "pinentry"
brew "pixman"
brew "pkg-config"
brew "postgresql"
brew "python"
brew "sops"
brew "step"
brew "stern"
brew "sysbench"
brew "thoughtbot/formulae/rcm"
brew "tree"
brew "unixodbc"
brew "unzip"
brew "vmware-tanzu/carvel/ytt"
brew "watch"
brew "wget"
brew "wxmac"
brew "yarn"
brew "youtube-dl"
brew "yq"
brew "zsh-completions"
brew "zsh"

# cask "onyx"
cask "1password-cli"
cask "1password"
cask "adguard-vpn"
cask "adguard"
cask "adobe-creative-cloud"
cask "battle-net"
cask "canon-eos-webcam-utility"
cask "chromedriver"
cask "discord"
cask "docker"
cask "expressvpn"
cask "figma"
cask "firefox"
cask "font-fira-code"
cask "google-chrome"
cask "insomnia"
cask "iterm2"
cask "microsoft-auto-update"
cask "microsoft-office"
cask "obsidian"
cask "parsec"
cask "postman"
cask "rectangle"
cask "setapp"
cask "slack"
cask "steam"
cask "visual-studio-code"
cask "vlc"
cask "whatsapp"
cask "yandex-cloud-cli"

# mas "Keynote", id: 409183694
# mas "Monosnap", id: 540348655
# mas "NextDNS", id: 1464122853
# mas "Numbers", id: 409203825
# mas "Pages", id: 409201541
# mas "Reeder 5", id: 1529448980
# mas "Tweetbot", id: 1384080005
# mas "Xcode", id: 497799835
