#!/usr/bin/env zsh
if [ -z "${KOPS_STATE_STORE}" ]; then
  echo "Set KOPS_STATE_STORE in dotfiles-private or .zshrc.local"
  return 1
fi
AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
export AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)
export AWS_SECRET_ACCESS_KEY
