#!/usr/bin/env zsh
AWS_ACCESS_KEY_ID=$(aws configure get aws_access_key_id)
export AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY=$(aws configure get aws_secret_access_key)
export AWS_SECRET_ACCESS_KEY
export KOPS_STATE_STORE=s3://fewlines-co-state-store
