[settings]
not_found_auto_install = true
trusted_config_paths = ["~/Workspace/tgautier"]

[tools]
dart = "3.11.6"
deno = "2.7.14"
elixir = "1.19.5-otp-28"
erlang = "28.5"
"vfox:mise-plugins/vfox-flutter" = "3.41.9"
go = "1.26.3"
helm = "4.1.4"
node = "26"
python = "3.14.5"
ruby = "4.0.3"
yarn = "4.14.1"
yq = "4.53.2"
